# Generated by Django 4.2.11 on 2024-03-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_author_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Yazar', 'verbose_name_plural': 'Yazarlar'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('title',), 'verbose_name': 'Bloq', 'verbose_name_plural': 'Bloqlar'},
        ),
    ]
